// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onptfjkvnmrshsdspqlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucHRmamt2bm1yc2hzZHNwcWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNjgxNTUsImV4cCI6MjA3NTk0NDE1NX0.Srblr47sX2ywG-o5Pv-KA3NuJ21ogGKuhBB0klzks_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});