// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqbjopnmzccegocyqrqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxYmpvcG5temNjZWdvY3lxcnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NDA1NDYsImV4cCI6MjA3NzUxNjU0Nn0.lV0WSSRLSdUEx_pjprto5CzSHj1fRdy15n7YO_1JjPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});